# air.toml

[build]
  bin = "tmp/main"
  cmd = "swag init -g cmd/main.go && go build -o tmp/main ./cmd"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["tmp", "docs", "vendor", "node_modules", "postman"]
  exclude_file = []
  follow_symlink = true
  exclude_regex = []
  delay = 1000
  poll = true
  stop_on_error = true

[log]
  time = true
  color = true

[misc]
  clean_on_exit = true
