name: codematic

services:
  codematic:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: codematic-app
    ports:
      - "9081:8080"
    env_file: .env
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - KAFKA_BROKER=${KAFKA_BROKER:-kafka:9092}
    depends_on:
      - redis
      - postgres
      - kafka

  codematic-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: codematic-dev
    volumes:
      - .:/app
      - air-tmp:/app/tmp
    ports:
      - "9082:8092"
    env_file: .env
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - KAFKA_BROKER=${KAFKA_BROKER:-kafka:9092}
    depends_on:
      - redis
      - postgres
      - grafana
      - prometheus
      - kafka
    command: ["air"]

  postgres:
    image: postgres:16.2-alpine
    container_name: codematic-db
    ports:
      - "5433:5432"
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    container_name: codematic-redis
    ports:
      - "9084:6379"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: codematic-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9086:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: codematic-grafana
    ports:
      - "9087:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: codematic-kafka
    ports:
      - "9088:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv  
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  redis-data:
  es-data:
  pgdata:
  air-tmp:
  grafana-storage:
  kafka-data:
