// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Action    string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type Currency struct {
	Code      string
	Name      string
	Symbol    string
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	UserID         pgtype.UUID
	IdempotencyKey string
	Endpoint       string
	RequestHash    string
	ResponseBody   []byte
	StatusCode     pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Provider struct {
	ID        pgtype.UUID
	Name      string
	Code      string
	Config    []byte
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Transaction struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WalletID     pgtype.UUID
	ProviderID   pgtype.UUID
	CurrencyCode string
	Reference    string
	Type         string
	Status       string
	Amount       decimal.Decimal
	Fee          decimal.Decimal
	Metadata     []byte
	ErrorReason  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Transfer struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	SenderWalletID   pgtype.UUID
	ReceiverWalletID pgtype.UUID
	TransactionID    pgtype.UUID
	Amount           decimal.Decimal
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Email        string
	Phone        pgtype.Text
	PasswordHash string
	Role         pgtype.Text
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type VirtualAccount struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	UserID        pgtype.UUID
	ProviderID    pgtype.UUID
	AccountNumber string
	BankName      string
	Currency      string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Wallet struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	WalletTypeID pgtype.UUID
	Balance      decimal.Decimal
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WalletType struct {
	ID          pgtype.UUID
	Name        string
	Currency    string
	IsActive    pgtype.Bool
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WebhookEvent struct {
	ID              pgtype.UUID
	ProviderID      pgtype.UUID
	ProviderEventID string
	TenantID        pgtype.UUID
	EventType       string
	Payload         []byte
	Status          string
	Attempts        pgtype.Int4
	LastError       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
